ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_CARGO 
FOREIGN KEY (ID_CARGO) REFERENCES CARGO(IDCARGO)
GO

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
GO

ALTER TABLE DEPENDENTE
ADD CONSTRAINT FK_DEPENDENTE_FUNCIONARIO
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
GO

ALTER TABLE TELEFONE_FUNC
ADD CONSTRAINT FK_TELEFONE_FUNC_FUNCIONARIO
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
GO

ALTER TABLE FALTA
ADD CONSTRAINT FK_FALTA_FUNCIONARIO
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
GO

ALTER TABLE SALARIO
ADD CONSTRAINT FK_SALARIO_FUNCIONARIO
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
GO

ALTER TABLE SALARIO
ADD CONSTRAINT CHECK_SALARIO
CHECK(DATA_FIM IS NULL OR DATA_FIM > DATA_INICIO)
GO

ALTER TABLE DEPENDENTE 
ADD CONSTRAINT CK_PARENTESCO
CHECK(PARENTESCO IN('Filho','Filha','Conjuge'))
GO

ALTER TABLE FALTA
ADD CONSTRAINT CK_MOTIVO
CHECK (MOTIVO IN (
    'Doença',
    'Consulta médica',
    'Atraso',
    'Problemas pessoais',
    'Falta não justificada'
))
GO
