-- =========================================
-- 04 - QUERIES
-- Projeto: Sistema de RH
-- Autor: Luis
-- =========================================

/* Listar todos os funcionários com seus cargos */

SELECT F.NOME AS FUNCIONARIO, C.NOME_CARGO AS CARGO
FROM FUNCIONARIO F
INNER JOIN CARGO C
ON F.ID_CARGO = C.IDCARGO
GO

/* Listar funcionários e seus dependentes - mesmo que os que não tenha dependentes */

SELECT F.NOME AS FUNCIONARIOS, D.NOME_DEPENDENTE AS DEPENDENTES, D.PARENTESCO 
FROM FUNCIONARIO F
LEFT JOIN DEPENDENTE D
ON F.IDFUNCIONARIO = D.ID_FUNCIONARIO
GO

/* Quantidade de dependentes por funcionário */

SELECT F.NOME,COUNT(IDDEPENDENTES) AS QTD_DEPENDENTE
FROM FUNCIONARIO F
LEFT JOIN DEPENDENTE D
ON F.IDFUNCIONARIO = D.ID_FUNCIONARIO
GROUP BY NOME
ORDER BY QTD_DEPENDENTE
GO

/* Total de faltas por funcionário */

SELECT F.NOME AS FUNCIONARIOS,COUNT(IDFALTA) AS TOTAL_FALTAS
FROM FUNCIONARIO F
LEFT JOIN FALTA FA
ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO
GROUP BY F.NOME
GO

/* trazer nome, cargo, departamento, salario atual, total beneficio, qtd faltas */

SELECT 
    F.NOME AS FUNCIONARIO,
    C.NOME_CARGO AS CARGO,
    D.NOME_DEPART AS DEPARTAMENTO,
    S.VALOR AS SALARIO_ATUAL,
    ISNULL(B.TOTAL_BENEFICIO, 0) AS TOTAL_BENEFICIO,
    ISNULL(FA.TOTAL_FALTA, 0) AS TOTAL_FALTA
FROM FUNCIONARIO F
INNER JOIN CARGO C
    ON F.ID_CARGO = C.IDCARGO
INNER JOIN DEPARTAMENTO D
    ON F.ID_DEPARTAMENTO = D.IDDEPARTAMENTO
INNER JOIN SALARIO S
    ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
    AND S.DATA_FIM IS NULL

LEFT JOIN (
    SELECT 
        ID_FUNCIONARIO,
        SUM(VALOR) AS TOTAL_BENEFICIO
    FROM FUNCIONARIO_BENEFICIO
    WHERE DATA_FIM IS NULL
    GROUP BY ID_FUNCIONARIO
) B 
    ON F.IDFUNCIONARIO = B.ID_FUNCIONARIO


LEFT JOIN (
    SELECT 
        ID_FUNCIONARIO,
        COUNT(*) AS TOTAL_FALTA
    FROM FALTA
    GROUP BY ID_FUNCIONARIO
) FA 
    ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO

ORDER BY TOTAL_BENEFICIO DESC, TOTAL_FALTA DESC
GO

/* CLASSIFICAÇÃO SALARIAL / CLASSIFICAÇÃO DE FALTAS */

SELECT F.NOME AS FUNCIONARIOS,S.VALOR AS SALARIO_ATUAL, COUNT(FA.IDFALTA) AS TOTAL_FALTAS,
	   CASE
			WHEN S.VALOR < 3000 THEN 'BAIXO'
			WHEN S.VALOR <= 7000 THEN 'MÉDIO'
			ELSE 'ALTO'
		END AS CLASSIFICAÇÃO_SALARIAL,
		CASE
			WHEN COUNT(FA.IDFALTA) = 0 THEN 'EXCELENTE'
			WHEN COUNT(FA.IDFALTA) <= 3 THEN 'ATENÇÃO'
			WHEN COUNT(FA.IDFALTA) > 3 THEN 'CRÍTICO'
		END AS CLASSIFICAÇÃO_FALTAS
FROM FUNCIONARIO F
INNER JOIN SALARIO S
ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
AND DATA_FIM IS NULL
LEFT JOIN FALTA FA
ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO
GROUP BY F.NOME,S.VALOR
ORDER BY TOTAL_FALTAS ASC
GO

/* UTILIZANDO CTE PARA CLASSIFICAÇÃO DE FUNCIONARIOS*/

WITH DADOS_FUNCIONARIOS AS(
	SELECT F.NOME AS FUNCIONARIO,
		   C.NOME_CARGO AS CARGO,
		   S.VALOR AS SALARIO_ATUAL,
		   COUNT(FA.IDFALTA) AS TOTAL_FALTA
	FROM FUNCIONARIO F
	INNER JOIN CARGO C
	ON F.ID_CARGO = C.IDCARGO
	INNER JOIN SALARIO S
	ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
	AND DATA_FIM IS NULL
	LEFT JOIN FALTA FA
	ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO
	GROUP BY F.NOME,C.NOME_CARGO,S.VALOR
)

SELECT FUNCIONARIO,
	   CARGO,
	   SALARIO_ATUAL,
	   TOTAL_FALTA,
	   CASE
			WHEN SALARIO_ATUAL <= 3000 THEN 'BAIXO'
			WHEN SALARIO_ATUAL <= 6000 THEN 'MÉDIO'
			ELSE 'ALTO'
	   END AS CLASSIFICACAO
INTO #RELATORIO_FUNCIONARIO -- INSERINDO OS DADOS EM UMA TABELA TEMPORARIA
FROM DADOS_FUNCIONARIOS
GO

SELECT * FROM #RELATORIO_FUNCIONARIO
WHERE CLASSIFICACAO = 'ALTO'
GO

/* Total de benefícios por funcionário
Soma dos valores*/

WITH DADOS_BENEFICIOS AS(
	SELECT F.NOME,
		   (FB.ID_BENEFICIO) AS TOTAL_BENEFICIO,
		   SUM(FB.VALOR) VALOR_TOTAL
	FROM FUNCIONARIO F
	INNER JOIN FUNCIONARIO_BENEFICIO FB
	ON F.IDFUNCIONARIO = FB.ID_FUNCIONARIO
	GROUP BY F.NOME

)

SELECT NOME,
	   TOTAL_BENEFICIO,
	   VALOR_TOTAL
FROM DADOS_BENEFICIOS
WHERE VALOR_TOTAL > 200
GO

/* SUBQUERYS */

/* 1. Funcionários acima da média salarial */

SELECT F.NOME AS FUNCIONARIO, S.VALOR AS SALARIO
FROM FUNCIONARIO F
INNER JOIN SALARIO S
ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
WHERE VALOR > ( SELECT AVG(VALOR) AS MEDIA_SALARIAL
				FROM SALARIO
				WHERE DATA_FIM IS NULL)
GO

/*2. Funcionário com maior salário*/


SELECT NOME, VALOR AS MAIOR_SALARIO
FROM FUNCIONARIO
INNER JOIN SALARIO
ON IDFUNCIONARIO = ID_FUNCIONARIO
WHERE VALOR = (SELECT MAX(VALOR)
			   FROM SALARIO
			   WHERE DATA_FIM IS NULL)
GROUP BY NOME,VALOR
GO

/* 3. Funcionários com mais faltas que a média */

SELECT 
    F.NOME,
    COUNT(FA.IDFALTA) AS TOTAL_FALTAS
FROM FUNCIONARIO F
LEFT JOIN FALTA FA
    ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO
GROUP BY F.NOME
HAVING COUNT(FA.IDFALTA) > (
    SELECT AVG(QTD_FALTAS)
    FROM (
        SELECT COUNT(*) AS QTD_FALTAS
        FROM FALTA
        GROUP BY ID_FUNCIONARIO
    ) AS MEDIA
)

/* Funcionários com salário acima de 5000 */

WITH SALARIO_ATUAL AS (
	SELECT F.NOME AS FUNCIONARIO,S.VALOR AS SALARIO_ATUAL
	FROM FUNCIONARIO F
	INNER JOIN SALARIO S
	ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
	WHERE DATA_FIM IS NULL
	GROUP BY F.NOME, S.VALOR

)

SELECT FUNCIONARIO,SALARIO_ATUAL
FROM SALARIO_ATUAL
WHERE SALARIO_ATUAL > 5000
ORDER BY SALARIO_ATUAL DESC
GO

/* FUNCIONARIO SEM DEPENDENTE */

WITH TOTAL_DEPENDENTE AS(
	SELECT ID_FUNCIONARIO, COUNT(*) AS QTD_DEPENDENTES
	FROM DEPENDENTE
	GROUP BY ID_FUNCIONARIO


)

SELECT F.NOME
FROM FUNCIONARIO F
LEFT JOIN TOTAL_DEPENDENTE TD
ON F.IDFUNCIONARIO = TD.ID_FUNCIONARIO
WHERE TD.QTD_DEPENDENTES IS NULL
GO
