CREATE PROCEDURE ADMITIR_FUNC
	   @NOME VARCHAR(50),
	   @CPF VARCHAR(15),
	   @SEXO CHAR(1),
	   @DATA_NASCIMENTO DATE,
	   @EMAIL VARCHAR(50),
	   @STATUS VARCHAR(10),
	   @ID_CARGO INT,
	   @ID_DEPARTAMENTO INT,
	   @SALARIO DECIMAL(10,2)

AS
BEGIN
		INSERT INTO FUNCIONARIO(NOME,CPF,SEXO,DATA_NASCIMENTO,DATA_ADMISSAO,EMAIL,STATUS,ID_CARGO,ID_DEPARTAMENTO) 
		VALUES (@NOME,@CPF,@SEXO,@DATA_NASCIMENTO,GETDATE(),@EMAIL,@STATUS,@ID_CARGO,@ID_DEPARTAMENTO)

		DECLARE @ID_FUNC INT = SCOPE_IDENTITY()

		INSERT INTO SALARIO(DATA_INICIO,VALOR,ID_FUNCIONARIO)
		VALUES (GETDATE(),@SALARIO,@ID_FUNC)
END
GO

EXEC ADMITIR_FUNC 'Marcos Vinícius Alcantara','4453245676','M','2002-02-20','marcosvini@gmail.com','Ativo',5,1,4000.00
GO

EXEC ADMITIR_FUNC 'Julio Fernandes Lima','4653895676','M','2002-05-20','juliofern@gmail.com','Ativo',4,2,3000.00
GO
