CREATE PROCEDURE ATUALIZAR_SALARIO
	   @ID_FUNCIONARIO INT,
	   @NOVO_SALARIO DECIMAL(10,2)
AS
BEGIN
		UPDATE SALARIO
		SET DATA_FIM = GETDATE()
		WHERE ID_FUNCIONARIO = @ID_FUNCIONARIO
		AND DATA_FIM IS NULL
	    
		INSERT INTO SALARIO (DATA_INICIO,VALOR,ID_FUNCIONARIO)
		VALUES ( GETDATE(),@NOVO_SALARIO,@ID_FUNCIONARIO)
END
GO

EXEC ATUALIZAR_SALARIO 11,2800.00
