CREATE PROCEDURE REGISTRAR_FALTA
	   @ID_FUNCIONARIO INT,
	   @MOTIVO VARCHAR(50)
AS
BEGIN
		INSERT INTO FALTA (MOTIVO,DATA_FALTA,ID_FUNCIONARIO)
		VALUES (@MOTIVO,GETDATE(),@ID_FUNCIONARIO)
END
GO

EXEC REGISTRAR_FALTA 1,'Consulta médica'
